cursor #e3e2e7
cursor_text_color #c5c6d1

foreground            #e3e2e7
background            #121317
selection_foreground  #283046
selection_background  #bec6e3
url_color             #b2c5ff

color0   #121317
color1   #ff7298
color2   #7fff93
color3   #fff872
color4   #9ab0f2
color5   #344476
color6   #b2c5ff
color7   #eff3ff
color8   #404248
color9   #ff9fb9
color10  #a5ffb3
color11  #fffba5
color12  #bdcdff
color13  #c9d6ff
color14  #dce4ff
color15  #f8faff
